create table app.queue_audit_log
(
	 id bigint generated by default as identity
	,action smallint
	,user_id bigint
	,content_item_id bigint
	,create_date timestamp without time zone default (now() at time zone 'utc')
    ,_visited boolean default false
)